### PR TITLE
Relicense under CC0

### LINKED ISSUE #2: Relicense under a Creative Commons license
During repository creation the Apache 2.0 was selected. But IIUC it's a poor fit for images. I suggest using CC-BY or CC-0 instead.

CC-BY is a bit less suitable for source code (e.g. for the image generation scripts), but it's used sometimes for this purpose. CC-BY also requires attribution and technically we must attribute ourselves when the images are used as part of `rand_distr` docs.

CC-0 will mean the least trouble for image users (including ourselves), but it means effectively publishing the images into the public domain. Personally, I am fine with it in this case, but some contributors may disagree.

### PR DESCRIPTION
**Pull request by newpavlov**
@MichaelOwenDyer (the main contributor of code and images) has given his consent [here](https://github.com/rust-random/charts/issues/2#issuecomment-2049424940).

The license text is taken from [here](https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt),

Closes #2

### CODE REVIEW

**Comment by dhardy** [comment]
We should add a README with a snippet about the licence. Creative commons suggests this:

> <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://github.com/rust-random/charts">Graphical representations of distributions</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://github.com/MichaelOwenDyer">Michael Owen Dyer</a> is marked with <a href="https://creativecommons.org/publicdomain/zero/1.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC0 1.0</a></p> 

Probably the LICENSE should exactly match that from CC?
```
$ diff legalcode.txt LICENSE
1,2d0
< Creative Commons Legal Code
< 
4,12d1
< 
<     CREATIVE COMMONS CORPORATION IS NOT A LAW FIRM AND DOES NOT PROVIDE
<     LEGAL SERVICES. DISTRIBUTION OF THIS DOCUMENT DOES NOT CREATE AN
<     ATTORNEY-CLIENT RELATIONSHIP. CREATIVE COMMONS PROVIDES THIS
<     INFORMATION ON AN "AS-IS" BASIS. CREATIVE COMMONS MAKES NO WARRANTIES
<     REGARDING THE USE OF THIS DOCUMENT OR THE INFORMATION OR WORKS
<     PROVIDED HEREUNDER, AND DISCLAIMS LIABILITY FOR DAMAGES RESULTING FROM
<     THE USE OF THIS DOCUMENT OR THE INFORMATION OR WORKS PROVIDED
<     HEREUNDER.
```

Also, @MichaelOwenDyer needs to approve this.

**Comment by newpavlov** [comment]
>We should add a README with a snippet about the licence

I don't think it's worth to create a README with just licensing information. It's what the LICENSE file is for. It's probably better to add a proper README in a separate PR.

>Probably the LICENSE should exactly match that from CC?

I've seen several LICENSE files in which this preamble was removed, but I guess it's fine to keep it as well.

**Comment by MichaelOwenDyer** [comment]
Will gladly approve this - but I feel obligated to mention that I used (and linked) some code I found on the internet in https://github.com/rust-random/charts/blob/main/src/distributions/dirichlet.py, in case this has any legal relevance here (I am not a lawyer).

**Comment by MichaelOwenDyer** [comment]
The code in question which I adapted is found here: https://gist.github.com/tboggs/8778945. Since it is a gist I don't see any license in particular associated with it. What do you think @newpavlov?

**Comment by newpavlov** [comment]
I am not sure... _Technically_, if no licensing information is provided, then we have no right to use this code at all (even worse,  this also applies to images generated by it). But I think that _intention_ of the author was to share this code freely. We also attribute original source in the code comments. Ideally, @tboggs would provide his consent, but, unfortunately, it does not look like he has any recent activity on GitHub.

**Comment by tboggs** [comment]
I just added MIT license text to the gist in question. I assume that should suffice for what you need. If not, let me know.

**Comment by newpavlov** [comment]
@tboggs 
It would be ideal if you allow us to use the code under CC0 (the same license under which we want to distribute the generated images), but I think we could use a separate license for source code by adding MIT license terms (with appropriate attribution) to the source files header.

**Comment by MichaelOwenDyer** [comment]
If @tboggs prefers to keep MIT (which of course is his right to do) then I would suggest we add the MIT terms to the top of https://github.com/rust-random/charts/blob/main/src/distributions/dirichlet.py and put the rest of the repository under CC0. I hope something like that would fly legally.

By the way, thanks a lot for sharing the Dirichlet code way back in 2014 @tboggs 😄 I was struggling for days to get that to work until I found your post!

**Review by MichaelOwenDyer — APPROVED** [review]
Looks good now, thanks!

**Pull request merged**
